spring:
    jpa:
        hibernate:
            ddl-auto: none #can be update or validate or delete
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/capstone
        username: root
        password: adminroot
        driver-class-name: com.mysql.cj.jdbc.Driver

    application:
        name: Product

    url:
        fakeStore:
            specificProduct: "https://fakestoreapi.com/products/{id}"
            product: "https://fakestoreapi.com/products"

server:
    port: 8080